### ISSUE TITLE
Devolucion projecto integrador

### ISSUE THREAD

**Issue by garciagabriel** [DanielaMadelaine/Biblioteca-Modelo#1]
La implementacion esta bien, podrias haber agregado mas excepciones en vez de tener solo BibliotecaException , de esa forma podrias distinguir mejor los diferentes tipos de errores, y te ayudaria cuando aumente la complejidad del codigo.

**Comment by DanielaMadelaine** [comment]
Lo voy a tener en cuenta, muchas gracias gabriel, saludos :)
